import type { AutoRouterCandidateConfig } from './api';
import {
  isGlm52ModelId,
  isGlm5ModelId,
  splitGlmModelRef,
} from '../../shared/glmModelPreference';

export {
  isGlm52ModelId,
  isGlm5ModelId,
} from '../../shared/glmModelPreference';

export interface GlmRouterCandidatePreferenceSummary {
  keptCount: number;
  suppressedCount: number;
  suppressedModelIds: string[];
  preferredProviderIds: string[];
}

export interface GlmSuppressedCandidateListDisplay {
  visibleText: string;
  accessibilityText: string;
  fullText: string;
  hiddenCount: number;
}

export function formatGlmSuppressedCandidateList(
  modelIds: string[],
  maxVisible = 3,
): GlmSuppressedCandidateListDisplay {
  const sortedModelIds = [...modelIds].sort((a, b) => a.localeCompare(b));
  const fullText = sortedModelIds.join(', ');
  const visibleLimit = Math.max(0, Math.floor(maxVisible));
  const visibleModelIds = sortedModelIds.slice(0, visibleLimit);
  const hiddenCount = Math.max(0, sortedModelIds.length - visibleModelIds.length);
  const visiblePrefix = visibleModelIds.join(', ');
  const visibleText = hiddenCount > 0
    ? [visiblePrefix, `+${hiddenCount} more`].filter(Boolean).join(', ')
    : visiblePrefix;

  return {
    visibleText,
    accessibilityText: fullText,
    fullText,
    hiddenCount,
  };
}

export function pickPreferredGlm52RouterCandidate(
  candidates: AutoRouterCandidateConfig[],
): string {
  return candidates.find((candidate) => isGlm52ModelId(candidate.modelId))?.modelId
    || candidates[0]?.modelId
    || '';
}

export function summarizeAutoGeneratedGlmRouterCandidatePreference(
  candidates: AutoRouterCandidateConfig[],
): GlmRouterCandidatePreferenceSummary {
  const providersWithGlm52 = new Set<string>();
  for (const candidate of candidates) {
    if (isGlm52ModelId(candidate.modelId)) {
      providersWithGlm52.add(splitGlmModelRef(candidate.modelId).providerId);
    }
  }

  const suppressedByKey = new Map<string, string>();
  const uniqueCandidateKeys = new Set<string>();
  for (const candidate of candidates) {
    uniqueCandidateKeys.add(candidate.modelId.trim().toLowerCase());
  }
  for (const candidate of candidates) {
    if (!isGlm5ModelId(candidate.modelId) || isGlm52ModelId(candidate.modelId)) continue;
    if (!providersWithGlm52.has(splitGlmModelRef(candidate.modelId).providerId)) continue;
    const normalizedModelId = candidate.modelId.trim().toLowerCase();
    if (!suppressedByKey.has(normalizedModelId)) {
      suppressedByKey.set(normalizedModelId, candidate.modelId);
    }
  }
  const suppressedModelIds = [...suppressedByKey.values()].sort((a, b) => a.localeCompare(b));

  return {
    keptCount: uniqueCandidateKeys.size - suppressedModelIds.length,
    suppressedCount: suppressedModelIds.length,
    suppressedModelIds,
    preferredProviderIds: [...providersWithGlm52].sort(),
  };
}

export function activeOlderSameProviderGlmCandidateIds(
  activeCandidates: AutoRouterCandidateConfig[],
  configuredCandidates: AutoRouterCandidateConfig[],
): string[] {
  const providersWithGlm52 = new Set<string>();
  for (const candidate of configuredCandidates) {
    if (isGlm52ModelId(candidate.modelId)) {
      providersWithGlm52.add(splitGlmModelRef(candidate.modelId).providerId);
    }
  }
  if (providersWithGlm52.size === 0) return [];

  const activeByKey = new Map<string, string>();
  for (const candidate of activeCandidates) {
    if (!isGlm5ModelId(candidate.modelId) || isGlm52ModelId(candidate.modelId)) continue;
    if (!providersWithGlm52.has(splitGlmModelRef(candidate.modelId).providerId)) continue;
    const normalizedModelId = candidate.modelId.trim().toLowerCase();
    if (!activeByKey.has(normalizedModelId)) {
      activeByKey.set(normalizedModelId, candidate.modelId);
    }
  }

  return [...activeByKey.values()].sort((a, b) => a.localeCompare(b));
}

/**
 * The optional summary must be computed from the same candidates array.
 */
export function filterAutoGeneratedGlmRouterCandidates(
  candidates: AutoRouterCandidateConfig[],
  summary = summarizeAutoGeneratedGlmRouterCandidatePreference(candidates),
): AutoRouterCandidateConfig[] {
  if (summary.preferredProviderIds.length === 0) return candidates;
  const providersWithGlm52 = new Set(summary.preferredProviderIds);

  return candidates.filter((candidate) => {
    if (!isGlm5ModelId(candidate.modelId) || isGlm52ModelId(candidate.modelId)) return true;
    return !providersWithGlm52.has(splitGlmModelRef(candidate.modelId).providerId);
  });
}
