import type { AutoRouterCandidateConfig } from './api';
import {
  isMiniMaxM2SeriesModelId,
  isMiniMaxM3ModelId,
  splitMiniMaxModelRef,
} from '../../shared/minimaxModelPreference';

export {
  isMiniMaxM2SeriesModelId,
  isMiniMaxM3ModelId,
} from '../../shared/minimaxModelPreference';

export interface MiniMaxRouterCandidatePreferenceSummary {
  keptCount: number;
  suppressedCount: number;
  suppressedModelIds: string[];
  preferredProviderIds: string[];
}

export interface MiniMaxSuppressedCandidateListDisplay {
  visibleText: string;
  accessibilityText: string;
  fullText: string;
  hiddenCount: number;
}

export function formatMiniMaxSuppressedCandidateList(
  modelIds: string[],
  maxVisible = 3,
): MiniMaxSuppressedCandidateListDisplay {
  const sortedModelIds = [...modelIds].sort((a, b) => a.localeCompare(b));
  const fullText = sortedModelIds.join(', ');
  const visibleLimit = Math.max(0, Math.floor(maxVisible));
  const visibleModelIds = sortedModelIds.slice(0, visibleLimit);
  const hiddenCount = Math.max(0, sortedModelIds.length - visibleModelIds.length);
  const visiblePrefix = visibleModelIds.join(', ');
  const visibleText = hiddenCount > 0
    ? [visiblePrefix, `+${hiddenCount} more`].filter(Boolean).join(', ')
    : visiblePrefix;

  return {
    visibleText,
    accessibilityText: fullText,
    fullText,
    hiddenCount,
  };
}

export function pickPreferredMiniMaxM3RouterCandidate(
  candidates: AutoRouterCandidateConfig[],
): string {
  return candidates.find((candidate) => isMiniMaxM3ModelId(candidate.modelId))?.modelId
    || candidates[0]?.modelId
    || '';
}

export function summarizeAutoGeneratedMiniMaxRouterCandidatePreference(
  candidates: AutoRouterCandidateConfig[],
): MiniMaxRouterCandidatePreferenceSummary {
  const providersWithM3 = new Set<string>();
  for (const candidate of candidates) {
    if (isMiniMaxM3ModelId(candidate.modelId)) {
      providersWithM3.add(splitMiniMaxModelRef(candidate.modelId).providerId);
    }
  }

  const suppressedByKey = new Map<string, string>();
  const uniqueCandidateKeys = new Set<string>();
  for (const candidate of candidates) {
    uniqueCandidateKeys.add(candidate.modelId.trim().toLowerCase());
  }
  for (const candidate of candidates) {
    if (!isMiniMaxM2SeriesModelId(candidate.modelId)) continue;
    if (!providersWithM3.has(splitMiniMaxModelRef(candidate.modelId).providerId)) continue;
    const normalizedModelId = candidate.modelId.trim().toLowerCase();
    if (!suppressedByKey.has(normalizedModelId)) {
      suppressedByKey.set(normalizedModelId, candidate.modelId);
    }
  }
  const suppressedModelIds = [...suppressedByKey.values()].sort((a, b) => a.localeCompare(b));

  return {
    keptCount: uniqueCandidateKeys.size - suppressedModelIds.length,
    suppressedCount: suppressedModelIds.length,
    suppressedModelIds,
    preferredProviderIds: [...providersWithM3].sort(),
  };
}

export function activeOlderSameProviderMiniMaxCandidateIds(
  activeCandidates: AutoRouterCandidateConfig[],
  configuredCandidates: AutoRouterCandidateConfig[],
): string[] {
  const providersWithM3 = new Set<string>();
  for (const candidate of configuredCandidates) {
    if (isMiniMaxM3ModelId(candidate.modelId)) {
      providersWithM3.add(splitMiniMaxModelRef(candidate.modelId).providerId);
    }
  }
  if (providersWithM3.size === 0) return [];

  const activeByKey = new Map<string, string>();
  for (const candidate of activeCandidates) {
    if (!isMiniMaxM2SeriesModelId(candidate.modelId)) continue;
    if (!providersWithM3.has(splitMiniMaxModelRef(candidate.modelId).providerId)) continue;
    const normalizedModelId = candidate.modelId.trim().toLowerCase();
    if (!activeByKey.has(normalizedModelId)) {
      activeByKey.set(normalizedModelId, candidate.modelId);
    }
  }

  return [...activeByKey.values()].sort((a, b) => a.localeCompare(b));
}

/**
 * The optional summary must be computed from the same candidates array.
 */
export function filterAutoGeneratedMiniMaxRouterCandidates(
  candidates: AutoRouterCandidateConfig[],
  summary = summarizeAutoGeneratedMiniMaxRouterCandidatePreference(candidates),
): AutoRouterCandidateConfig[] {
  if (summary.preferredProviderIds.length === 0) return candidates;
  const providersWithM3 = new Set(summary.preferredProviderIds);

  return candidates.filter((candidate) => {
    if (!isMiniMaxM2SeriesModelId(candidate.modelId)) return true;
    return !providersWithM3.has(splitMiniMaxModelRef(candidate.modelId).providerId);
  });
}
