import type { AutoRouterConfig, AutoRouterCandidateConfig, ModelInfo } from './api';
import { glmOnboardingRouterCard, isGlm5ModelId } from '../../shared/glmModelPreference';
import { isMiniMaxM2SeriesModelId, isMiniMaxM3ModelId, miniMaxM3OnboardingDefaultCard } from '../../shared/minimaxModelPreference';
import { filterAutoGeneratedMiniMaxRouterCandidates } from './minimaxRouterCandidatePreference';

const CHEAP_TEXT_ROLE_IDS = new Set(['summarizer', 'title']);
const GLM_DEEP_ROLE_IDS = new Set(['planner', 'reviewer', 'reasoner']);
const LOCAL_PROVIDER_IDS = new Set(['ollama', 'lmstudio']);

export interface OnboardingRoleAssignmentOptions {
  localProviderIds?: string[];
}

export function chooseOnboardingActiveModel(models: ModelInfo[]): string {
  return models.find((model) => model?.id && isMiniMaxM3ModelId(model.id))?.id
    || models.find((model) => model?.id && !isMiniMaxM2SeriesModelId(model.id))?.id
    || models.find((model) => model?.id)?.id
    || '';
}

function normalizeProviderId(providerId: string | undefined): string {
  return String(providerId || '').trim().toLowerCase().replace(/\s+/g, '');
}

function isLocalModel(model: ModelInfo | null | undefined, localProviderIds: Set<string>): boolean {
  if (!model?.id) return false;
  const providerId = normalizeProviderId(model.providerId);
  const providerName = normalizeProviderId(model.providerName);
  return model.type === 'local'
    || localProviderIds.has(providerId)
    || localProviderIds.has(providerName)
    || LOCAL_PROVIDER_IDS.has(providerId)
    || LOCAL_PROVIDER_IDS.has(providerName);
}

function modelComparableCost(model: ModelInfo | null | undefined): number | null {
  if (!model?.id) return null;
  const inputCost = model.inputCostPerMTok;
  const outputCost = model.outputCostPerMTok;
  if (!Number.isFinite(inputCost) || !Number.isFinite(outputCost)) return null;
  return Number(inputCost) + Number(outputCost);
}

function cheapestComparableModel(models: ModelInfo[]): ModelInfo | null {
  return models.reduce<{ model: ModelInfo | null; cost: number }>((best, model) => {
    const cost = modelComparableCost(model);
    if (cost == null) return best;
    if (!best.model || cost < best.cost) return { model, cost };
    return best;
  }, { model: null, cost: Number.POSITIVE_INFINITY }).model;
}

function modelRelativeRouterCost(model: ModelInfo | null | undefined): number {
  const cost = modelComparableCost(model);
  if (cost == null) return 0.5;
  return Math.max(0.02, Math.min(1, Number(cost.toFixed(2))));
}

function modelSupportsThinking(model: ModelInfo): boolean {
  const id = String(model.id || '').toLowerCase();
  const name = String(model.name || '').toLowerCase();
  return isGlm5ModelId(model.id)
    || isMiniMaxM3ModelId(model.id)
    || /reason|thinking|think|r1|r2|o3|o4|grok-4|deepseek-v4|qwen.*max/.test(`${id} ${name}`);
}

function onboardingRouterCard(model: ModelInfo): string {
  if (isMiniMaxM3ModelId(model.id)) {
    return miniMaxM3OnboardingDefaultCard();
  }
  if (isGlm5ModelId(model.id)) {
    return glmOnboardingRouterCard(model.id);
  }
  if (isLocalModel(model, new Set())) {
    return 'Local model: private on-machine fallback for routine work when local/private mode is selected. Validate harder tool-heavy tasks.';
  }
  return `${model.name || model.id} configured model: use for general text tasks when it fits cost, context, and capability needs.`;
}

function routerCandidateForModel(model: ModelInfo): AutoRouterCandidateConfig | null {
  if (!model?.id) return null;
  return {
    modelId: model.id,
    cost: modelRelativeRouterCost(model),
    supportsImages: Boolean(model.supportsImages),
    supportsThinking: modelSupportsThinking(model),
    card: onboardingRouterCard(model),
  };
}

function cheapestRouterCandidate(candidates: AutoRouterCandidateConfig[]): AutoRouterCandidateConfig | null {
  return [...candidates].sort((a, b) => a.cost - b.cost)[0] || null;
}

export function chooseAutoRouterRecommendedSelection(
  candidates: AutoRouterCandidateConfig[],
  activeModel = '',
): Pick<AutoRouterConfig, 'classifierModel' | 'defaultModel'> {
  const defaultModel = candidates.find((candidate) => isMiniMaxM3ModelId(candidate.modelId))?.modelId
    || (activeModel && !isMiniMaxM2SeriesModelId(activeModel) && candidates.some((candidate) => candidate.modelId === activeModel) ? activeModel : '')
    || candidates.find((candidate) => !isMiniMaxM2SeriesModelId(candidate.modelId))?.modelId
    || candidates[0]?.modelId
    || activeModel
    || '';
  const classifierModel = cheapestRouterCandidate(candidates)?.modelId || defaultModel;
  return { classifierModel, defaultModel };
}

function bestLocalModel(models: ModelInfo[], localProviderIds: Set<string>): ModelInfo | null {
  return models
    .filter((model) => isLocalModel(model, localProviderIds))
    .sort((a, b) => {
      const toolDelta = Number(Boolean(b.supportsTools)) - Number(Boolean(a.supportsTools));
      if (toolDelta !== 0) return toolDelta;
      return (b.contextWindowTokens || 0) - (a.contextWindowTokens || 0);
    })[0] || null;
}

export function chooseOnboardingRoleAssignments(
  models: ModelInfo[],
  optimizationPref: string | undefined,
  activeModel: string,
  roleIds: string[],
  options: OnboardingRoleAssignmentOptions = {},
): Record<string, string> {
  const fallbackModel = activeModel || chooseOnboardingActiveModel(models);
  const assignments = Object.fromEntries(roleIds.map((roleId) => [roleId, fallbackModel])) as Record<string, string>;
  if (!fallbackModel) return assignments;
  const localProviderIds = new Set((options.localProviderIds || []).map(normalizeProviderId));

  if (optimizationPref === 'local-private' && localProviderIds.size > 0) {
    const localModel = bestLocalModel(models, localProviderIds);
    if (localModel?.id) {
      for (const roleId of roleIds) assignments[roleId] = localModel.id;
    }
    return assignments;
  }

  const glmModel = models.find((model) => isGlm5ModelId(model?.id));
  if (glmModel?.id) {
    for (const roleId of roleIds) {
      if (GLM_DEEP_ROLE_IDS.has(roleId)) assignments[roleId] = glmModel.id;
    }
  }

  if (optimizationPref === 'low-cost') {
    const cheapModel = cheapestComparableModel(models);
    if (cheapModel?.id) {
      for (const roleId of roleIds) {
        if (CHEAP_TEXT_ROLE_IDS.has(roleId)) assignments[roleId] = cheapModel.id;
      }
    }
  }

  return assignments;
}

export function chooseOnboardingAutoRouterConfig(
  models: ModelInfo[],
  optimizationPref: string | undefined,
  activeModel: string,
  options: OnboardingRoleAssignmentOptions = {},
): AutoRouterConfig {
  const localProviderIds = new Set((options.localProviderIds || []).map(normalizeProviderId));
  const localModels = localProviderIds.size > 0 ? models.filter((model) => isLocalModel(model, localProviderIds)) : [];
  if (optimizationPref === 'local-private' && localModels.length === 0) {
    return {
      enabled: false,
      classifierModel: '',
      threshold: 0.7,
      defaultModel: activeModel || '',
      cacheTTLMs: 300_000,
      candidates: [],
    };
  }

  const candidateModels = optimizationPref === 'local-private' ? localModels : models;
  const candidates = filterAutoGeneratedMiniMaxRouterCandidates(
    candidateModels
      .map(routerCandidateForModel)
      .filter((candidate): candidate is AutoRouterCandidateConfig => Boolean(candidate)),
  );
  const selection = chooseAutoRouterRecommendedSelection(candidates, activeModel);

  return {
    enabled: candidates.length > 0,
    classifierModel: selection.classifierModel,
    threshold: 0.7,
    defaultModel: selection.defaultModel,
    cacheTTLMs: 300_000,
    candidates,
  };
}
