import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import type { AutoRouterCandidateConfig } from '../src/utils/api';
import {
  miniMaxM3ActiveOlderRoutingWarning,
  miniMaxM2FallbackPolicyDetail,
  miniMaxM2FallbackPolicyLabel,
  miniMaxM3PreferenceNoticeLabel,
  miniMaxM3PreferencePolicyDetail,
  miniMaxM3PreferencePolicyLabel,
  miniMaxM3SuppressionReason,
} from '../shared/minimaxModelPreference';
import {
  activeOlderSameProviderMiniMaxCandidateIds,
  filterAutoGeneratedMiniMaxRouterCandidates,
  formatMiniMaxSuppressedCandidateList,
  pickPreferredMiniMaxM3RouterCandidate,
  summarizeAutoGeneratedMiniMaxRouterCandidatePreference,
  isMiniMaxM2SeriesModelId,
  isMiniMaxM3ModelId,
} from '../src/utils/minimaxRouterCandidatePreference';

function candidate(modelId: string): AutoRouterCandidateConfig {
  return {
    modelId,
    cost: 0.2,
    supportsImages: true,
    supportsThinking: false,
    card: `${modelId} card`,
  };
}

function candidateWithCard(modelId: string, card: string): AutoRouterCandidateConfig {
  return {
    ...candidate(modelId),
    card,
  };
}

assert.equal(isMiniMaxM3ModelId('minimax:MiniMax-M3'), true, 'MiniMax-M3 should be recognized through provider-qualified ids');
assert.equal(isMiniMaxM3ModelId('MiniMax-M3'), true, 'MiniMax-M3 should be recognized through bare ids');
assert.equal(isMiniMaxM3ModelId('minimax:MiniMax-M30'), false, 'M30 should not be mistaken for M3');
assert.equal(isMiniMaxM2SeriesModelId('minimax:MiniMax-M2.7'), true, 'MiniMax-M2.7 should be recognized as older MiniMax');
assert.equal(isMiniMaxM2SeriesModelId('minimax:MiniMax-M2.7-highspeed'), true, 'MiniMax-M2.7 highspeed should be recognized as older MiniMax');
assert.equal(isMiniMaxM2SeriesModelId('minimax:MiniMax-M20'), false, 'M20 should not be mistaken for the M2.x line');
assert.equal(miniMaxM3PreferencePolicyLabel(), 'MiniMax M3 preferred', 'shared MiniMax policy copy should name M3 as the preferred lane');
assert.equal(miniMaxM3PreferenceNoticeLabel(), 'MiniMax M3 preference', 'shared Settings copy should name the MiniMax M3 preference notice consistently');
assert.match(
  miniMaxM3PreferencePolicyDetail(),
  /preferred over same-provider MiniMax M2\.x when M3 is viable/i,
  'shared MiniMax M3 policy detail should explain the same-provider M2.x boundary',
);
assert.equal(
  miniMaxM3SuppressionReason(),
  'because MiniMax M3 is configured on the same provider',
  'shared Settings copy should keep the MiniMax M3 suppression reason in one place',
);
assert.equal(
  miniMaxM3ActiveOlderRoutingWarning(),
  'This is informational only; active routing is unchanged. Review manual candidates or restore recommended defaults if you want MiniMax M3 to take over on that provider.',
  'shared Settings copy should keep the active older MiniMax warning in one place',
);
assert.equal(miniMaxM2FallbackPolicyLabel(), 'MiniMax M2 fallback', 'shared MiniMax policy copy should name older M2.x as fallback-only');
assert.match(
  miniMaxM2FallbackPolicyDetail(),
  /fallback when M3 is absent, filtered, or on a different provider namespace/i,
  'shared MiniMax M2 fallback detail should explain why older MiniMax can remain visible',
);

const withM3 = filterAutoGeneratedMiniMaxRouterCandidates([
  candidate('minimax:MiniMax-M3'),
  candidate('minimax:MiniMax-M2.7'),
  candidate('minimax:MiniMax-M2.7-highspeed'),
  candidate('z-ai-zhipu:glm-5.2'),
]);
assert.deepEqual(
  withM3.map((item) => item.modelId),
  ['minimax:MiniMax-M3', 'z-ai-zhipu:glm-5.2'],
  'Auto-generated MiniMax M2.x candidates should be suppressed when the same provider has MiniMax-M3',
);
assert.deepEqual(
  summarizeAutoGeneratedMiniMaxRouterCandidatePreference([
    candidate('minimax:MiniMax-M3'),
    candidate('minimax:MiniMax-M2.7'),
    candidate('minimax:MiniMax-M2.7-highspeed'),
    candidate('z-ai-zhipu:glm-5.2'),
  ]),
  {
    keptCount: 2,
    suppressedCount: 2,
    suppressedModelIds: ['minimax:MiniMax-M2.7', 'minimax:MiniMax-M2.7-highspeed'],
    preferredProviderIds: ['minimax'],
  },
  'MiniMax preference summary should report suppressed same-provider M2.x candidates for UI transparency',
);
assert.deepEqual(
  summarizeAutoGeneratedMiniMaxRouterCandidatePreference([
    candidateWithCard('MiniMax : MiniMax-M3', 'spaced M3 card'),
    candidateWithCard('minimax:MiniMax-M2.7-highspeed', 'highspeed card'),
    candidateWithCard('MiniMax:MiniMax-M2.7', 'duplicate first'),
    candidateWithCard('minimax:MiniMax-M2.7', 'duplicate second'),
  ]),
  {
    keptCount: 1,
    suppressedCount: 2,
    suppressedModelIds: ['MiniMax:MiniMax-M2.7', 'minimax:MiniMax-M2.7-highspeed'],
    preferredProviderIds: ['minimax'],
  },
  'MiniMax preference summary should normalize provider casing/spacing and return stable deduped model lists',
);
assert.deepEqual(
  activeOlderSameProviderMiniMaxCandidateIds(
    [
      candidate('minimax:MiniMax-M2.7'),
      candidate('minimax:MiniMax-M2.7-highspeed'),
      candidate('lab:MiniMax-M2.7'),
      candidate('minimax:MiniMax-M3'),
      candidate('MiniMax:MiniMax-M2.7'),
    ],
    [
      candidate('minimax:MiniMax-M3'),
      candidate('lab:MiniMax-M2.7'),
    ],
  ),
  ['minimax:MiniMax-M2.7', 'minimax:MiniMax-M2.7-highspeed'],
  'Active older same-provider MiniMax candidates should be reported when MiniMax M3 is configured on that provider',
);
assert.deepEqual(
  activeOlderSameProviderMiniMaxCandidateIds(
    [
      candidate('minimax:MiniMax-M2.7'),
      candidate('lab:MiniMax-M2.7'),
    ],
    [
      candidate('lab:MiniMax-M3'),
      candidate('minimax:MiniMax-M2.7'),
    ],
  ),
  ['lab:MiniMax-M2.7'],
  'Active older MiniMax candidates should only be reported for the provider namespace that has MiniMax M3 configured',
);
assert.deepEqual(
  activeOlderSameProviderMiniMaxCandidateIds(
    [
      candidate('minimax:MiniMax-M2.7'),
      candidate('z-ai-zhipu:glm-5.2'),
    ],
    [
      candidate('minimax:MiniMax-M2.7'),
      candidate('z-ai-zhipu:glm-5.2'),
    ],
  ),
  [],
  'Active older MiniMax candidates should stay quiet when no same-provider MiniMax M3 is configured',
);
const duplicateCaseCandidates = [
  candidateWithCard('MiniMax : MiniMax-M3', 'spaced M3 card'),
  candidateWithCard('minimax:MiniMax-M2.7-highspeed', 'highspeed card'),
  candidateWithCard('MiniMax:MiniMax-M2.7', 'duplicate first'),
  candidateWithCard('minimax:MiniMax-M2.7', 'duplicate second'),
  candidateWithCard('z-ai-zhipu:glm-5.2', 'GLM partner card'),
];
assert.deepEqual(
  filterAutoGeneratedMiniMaxRouterCandidates(
    duplicateCaseCandidates,
    summarizeAutoGeneratedMiniMaxRouterCandidatePreference(duplicateCaseCandidates),
  ).map((item) => item.modelId),
  filterAutoGeneratedMiniMaxRouterCandidates(duplicateCaseCandidates).map((item) => item.modelId),
  'Filtering with a precomputed MiniMax preference summary should match default filtering',
);
assert.deepEqual(
  formatMiniMaxSuppressedCandidateList([]),
  {
    visibleText: '',
    accessibilityText: '',
    fullText: '',
    hiddenCount: 0,
  },
  'empty suppressed candidate lists should not render placeholder text',
);
assert.deepEqual(
  formatMiniMaxSuppressedCandidateList([
    'minimax:MiniMax-M2.7-zeta',
    'minimax:MiniMax-M2.7-alpha',
    'minimax:MiniMax-M2.7-beta',
    'minimax:MiniMax-M2.7-gamma',
  ]),
  {
    visibleText: 'minimax:MiniMax-M2.7-alpha, minimax:MiniMax-M2.7-beta, minimax:MiniMax-M2.7-gamma, +1 more',
    accessibilityText: 'minimax:MiniMax-M2.7-alpha, minimax:MiniMax-M2.7-beta, minimax:MiniMax-M2.7-gamma, minimax:MiniMax-M2.7-zeta',
    fullText: 'minimax:MiniMax-M2.7-alpha, minimax:MiniMax-M2.7-beta, minimax:MiniMax-M2.7-gamma, minimax:MiniMax-M2.7-zeta',
    hiddenCount: 1,
  },
  'suppressed candidate formatter should show a stable sorted preview while keeping full accessibility text',
);
assert.equal(
  pickPreferredMiniMaxM3RouterCandidate([
    candidate('z-ai-zhipu:glm-5.2'),
    candidate('minimax:MiniMax-M3'),
    candidate('minimax:MiniMax-M2.7'),
  ]),
  'minimax:MiniMax-M3',
  'Settings should prefer the configured MiniMax-M3 candidate when it is present but not first',
);
assert.equal(
  pickPreferredMiniMaxM3RouterCandidate([
    candidate('z-ai-zhipu:glm-5.2'),
    candidate('minimax:MiniMax-M2.7'),
  ]),
  'z-ai-zhipu:glm-5.2',
  'Settings should fall back to the first configured candidate when MiniMax-M3 is unavailable',
);
assert.equal(
  pickPreferredMiniMaxM3RouterCandidate([]),
  '',
  'MiniMax preference selector should stay literal-free when no candidates are available',
);

const withoutM3 = filterAutoGeneratedMiniMaxRouterCandidates([
  candidate('minimax:MiniMax-M2.7'),
  candidate('z-ai-zhipu:glm-5.2'),
]);
assert.deepEqual(
  withoutM3.map((item) => item.modelId),
  ['minimax:MiniMax-M2.7', 'z-ai-zhipu:glm-5.2'],
  'MiniMax M2.x should remain an auto-router candidate when MiniMax-M3 is unavailable',
);

const differentProviderM3 = filterAutoGeneratedMiniMaxRouterCandidates([
  candidate('minimax:MiniMax-M2.7'),
  candidate('lab:MiniMax-M3'),
]);
assert.deepEqual(
  differentProviderM3.map((item) => item.modelId),
  ['minimax:MiniMax-M2.7', 'lab:MiniMax-M3'],
  'MiniMax M2.x should not be suppressed by MiniMax-M3 on a different provider namespace',
);

const settingsSource = readFileSync('src/components/SettingsModal.tsx', 'utf8');
assert.ok(
  settingsSource.includes('filterAutoGeneratedMiniMaxRouterCandidates(candidates, miniMaxPreference)'),
  'Settings auto-router scan should reuse the MiniMax preference summary when filtering auto-generated candidates',
);
assert.ok(
  settingsSource.includes('summarizeAutoGeneratedMiniMaxRouterCandidatePreference(candidates)'),
  'Settings auto-router scan should compute a MiniMax preference summary from raw configured candidates before filtering',
);
assert.ok(
  settingsSource.includes('miniMaxM3PreferenceNoticeLabel()'),
  'Settings auto-router UI should use the shared MiniMax M3 preference notice label',
);
assert.ok(
  settingsSource.indexOf('{configuredMiniMaxPreference.suppressedCount > 0 && (') < settingsSource.indexOf('{arEnabled && ('),
  'Settings auto-router UI should show the MiniMax M3 preference notice even before Auto-Router is enabled',
);
assert.ok(
  settingsSource.includes('const miniMaxPreferenceStatusParts = [')
    && settingsSource.includes('configuredMiniMaxPreference.suppressedCount > 0')
    && settingsSource.includes('activeOlderMiniMaxCandidateIds.length > 0')
    && settingsSource.includes("[miniMaxM3PreferenceNoticeLabel(), ...miniMaxPreferenceStatusParts].join('. ')"),
  'Settings auto-router status aria-label should be built from the same gated MiniMax suppression and active-drift messages as the visible card',
);
assert.ok(
  settingsSource.includes('configuredMiniMaxPreference.suppressedCount'),
  'Settings auto-router UI should expose the suppressed MiniMax candidate count',
);
assert.ok(
  settingsSource.includes('activeOlderSameProviderMiniMaxCandidateIdsForRouter(arCandidates, configuredCandidates)'),
  'Settings auto-router UI should compute active older same-provider MiniMax drift without changing active manual candidates',
);
assert.ok(
  settingsSource.includes('Active older MiniMax still routed'),
  'Settings auto-router UI should call out active older MiniMax candidates when MiniMax M3 is configured',
);
assert.ok(
  settingsSource.includes('miniMaxM3ActiveOlderRoutingWarning()'),
  'Settings auto-router UI should make the active MiniMax M2.x warning informational instead of silently mutating manual candidates',
);
assert.ok(
  settingsSource.includes('{(configuredMiniMaxPreference.suppressedCount > 0 || activeOlderMiniMaxCandidateIds.length > 0) && ('),
  'Settings auto-router UI should show the MiniMax M3 preference card when active older MiniMax drift exists even if configured suppression is empty',
);
assert.ok(
  settingsSource.includes('Preferred M3 provider') && settingsSource.includes('configuredMiniMaxPreference.preferredProviderIds.join'),
  'Settings auto-router UI should expose the provider ids that triggered the MiniMax M3 preference',
);
assert.ok(
  settingsSource.includes('configuredMiniMaxSuppressedCandidates.visibleText'),
  'Settings auto-router UI should render the compact MiniMax suppression preview',
);
assert.ok(
  settingsSource.includes('configuredMiniMaxSuppressedCandidates.accessibilityText'),
  'Settings auto-router status aria-label should keep the complete suppressed MiniMax candidate list',
);
assert.ok(
  settingsSource.includes('chooseAutoRouterRecommendedSelection(candidates)'),
  'Settings auto-router enable path should use the shared M3-default and cheap-classifier selector',
);
assert.ok(
  settingsSource.includes('classifierModel: currentAr?.classifierModel || arClassifier || recommended.classifierModel')
    && settingsSource.includes('defaultModel: currentAr?.defaultModel || arDefaultModel || recommended.defaultModel'),
  'Settings auto-router enable path should keep configured selections first and then fall back to recommended classifier/default selections',
);
assert.ok(
  settingsSource.includes('const recommended = chooseAutoRouterRecommendedSelection(scannedCandidates);'),
  'Settings initial auto-router candidate state should use the shared recommended selector',
);
assert.ok(
  settingsSource.includes('setArClassifier(recommended.classifierModel);')
    && settingsSource.includes('setArDefaultModel(recommended.defaultModel);'),
  'Settings initial auto-router candidate state should seed classifier and default from the recommended selection',
);
assert.ok(
  settingsSource.includes('const syncPreferredCandidateModelId = pickPreferredMiniMaxM3RouterCandidate(updated);'),
  'Settings configured-model sync should compute the MiniMax-M3 preference from the merged candidate list',
);
assert.ok(
  settingsSource.includes('resolveRouterSelection(arClassifier, updated, syncPreferredCandidateModelId)'),
  'Settings configured-model sync should prefer MiniMax-M3 when the classifier selection is missing or invalid',
);
assert.ok(
  settingsSource.includes('resolveRouterSelection(arDefaultModel, updated, nextClassifier)'),
  'Settings configured-model sync should preserve valid default selections and otherwise follow the MiniMax-M3-aware classifier fallback',
);
assert.ok(
  !settingsSource.includes('filterAutoGeneratedMiniMaxRouterCandidates([...existing, ...configured])'),
  'Manual or existing router candidates should not be suppressed by the MiniMax preference filter',
);
for (const localSettingsMiniMaxLiteral of [
  "['MiniMax M3 preference', ...miniMaxPreferenceStatusParts].join('. ')",
  '<span>MiniMax M3 preference</span>',
  'because MiniMax M3 is configured on the same provider',
  'This is informational only; active routing is unchanged. Review manual candidates or restore recommended defaults if you want MiniMax M3 to take over on that provider.',
]) {
  assert.ok(
    !settingsSource.includes(localSettingsMiniMaxLiteral),
    `Settings MiniMax preference card should not own shared copy locally: ${localSettingsMiniMaxLiteral}`,
  );
}

console.log('MiniMax router candidate preference checks passed.');
