import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import type { AutoRouterCandidateConfig } from '../src/utils/api';
import {
  glm52PreferenceNoticeLabel,
  glm52SuppressionReason,
  glmActiveOlderRoutingWarning,
  glmPatienceCandidateStatusLabel,
  glmPatienceSettingsIntro,
  glmPatienceSettingsTitle,
} from '../shared/glmModelPreference';
import {
  activeOlderSameProviderGlmCandidateIds,
  filterAutoGeneratedGlmRouterCandidates,
  formatGlmSuppressedCandidateList,
  pickPreferredGlm52RouterCandidate,
  summarizeAutoGeneratedGlmRouterCandidatePreference,
  isGlm5ModelId,
  isGlm52ModelId,
} from '../src/utils/glmRouterCandidatePreference';

function candidate(modelId: string): AutoRouterCandidateConfig {
  return {
    modelId,
    cost: 0.2,
    supportsImages: false,
    supportsThinking: true,
    card: `${modelId} card`,
  };
}

function candidateWithCard(modelId: string, card: string): AutoRouterCandidateConfig {
  return {
    ...candidate(modelId),
    card,
  };
}

assert.equal(isGlm52ModelId('z-ai-zhipu:glm-5.2'), true, 'GLM-5.2 should be recognized through provider-qualified ids');
assert.equal(isGlm52ModelId('glm-5.2'), true, 'GLM-5.2 should be recognized through bare ids');
assert.equal(isGlm52ModelId('glm-5.20'), false, 'GLM-5.20 should not be mistaken for GLM-5.2');
assert.equal(isGlm5ModelId('zhipu:glm-5.1'), true, 'GLM-5.1 should be recognized as a GLM-5 family candidate');
assert.equal(isGlm5ModelId('zhipu:glm-4.7'), false, 'GLM-4.7 should not be treated as the GLM-5 patience lane');
assert.equal(
  glmPatienceSettingsTitle('z-ai-zhipu:glm-5.2'),
  'GLM-5.2 patient partner. Give GLM the extended wait before treating slow responses as failure.',
  'shared Settings GLM copy should compose the model-specific patient-partner title',
);
assert.equal(
  glmPatienceSettingsIntro(),
  'GLM is a slower specialist for deep planning, review, and reasoning. Keep it in the patient lane so routing gives it time to finish careful work before fallback.',
  'shared Settings GLM copy should keep the patience-lane intro in one place',
);
assert.equal(
  glmPatienceCandidateStatusLabel('z-ai-zhipu:glm-5.2', 3, 2, 1),
  'GLM-5.2 patience lane configured for 3 GLM candidates. Active 2; configured 1',
  'shared Settings GLM copy should format the candidate-count aria summary',
);
assert.equal(
  glm52PreferenceNoticeLabel(),
  'GLM-5.2 preference',
  'shared Settings GLM copy should name the GLM-5.2 preference notice consistently',
);
assert.equal(
  glm52SuppressionReason(),
  'because GLM-5.2 is configured on the same provider',
  'shared Settings GLM copy should keep the GLM-5.2 suppression reason in one place',
);
assert.equal(
  glmActiveOlderRoutingWarning(),
  'This does not change active routing. Review manual candidates or restore recommended defaults if you want GLM-5.2 to take over on that provider.',
  'shared Settings GLM copy should keep the active older-GLM warning in one place',
);

const withGlm52 = filterAutoGeneratedGlmRouterCandidates([
  candidate('z-ai-zhipu:glm-5.2'),
  candidate('z-ai-zhipu:glm-5.1'),
  candidate('z-ai-zhipu:glm-5'),
  candidate('minimax:MiniMax-M3'),
]);
assert.deepEqual(
  withGlm52.map((item) => item.modelId),
  ['z-ai-zhipu:glm-5.2', 'minimax:MiniMax-M3'],
  'Auto-generated older same-provider GLM-5 candidates should be suppressed when GLM-5.2 is configured',
);
assert.deepEqual(
  summarizeAutoGeneratedGlmRouterCandidatePreference([
    candidate('z-ai-zhipu:glm-5.2'),
    candidate('z-ai-zhipu:glm-5.1'),
    candidate('z-ai-zhipu:glm-5'),
    candidate('minimax:MiniMax-M3'),
  ]),
  {
    keptCount: 2,
    suppressedCount: 2,
    suppressedModelIds: ['z-ai-zhipu:glm-5', 'z-ai-zhipu:glm-5.1'],
    preferredProviderIds: ['z-ai-zhipu'],
  },
  'GLM preference summary should report suppressed same-provider older GLM-5 candidates for UI transparency',
);
assert.deepEqual(
  summarizeAutoGeneratedGlmRouterCandidatePreference([
    candidateWithCard('Z-AI-Zhipu : glm-5.2', 'spaced GLM-5.2 card'),
    candidateWithCard('z-ai-zhipu:glm-5.1', 'duplicate first'),
    candidateWithCard('Z-AI-Zhipu:glm-5.1', 'duplicate second'),
    candidateWithCard('z-ai-zhipu:glm-5', 'base glm-5 card'),
  ]),
  {
    keptCount: 1,
    suppressedCount: 2,
    suppressedModelIds: ['z-ai-zhipu:glm-5', 'z-ai-zhipu:glm-5.1'],
    preferredProviderIds: ['z-ai-zhipu'],
  },
  'GLM preference summary should normalize provider casing/spacing and return stable deduped model lists',
);
assert.deepEqual(
  activeOlderSameProviderGlmCandidateIds(
    [
      candidate('z-ai-zhipu:glm-5.1'),
      candidate('z-ai-zhipu:glm-5'),
      candidate('lab:glm-5.1'),
      candidate('z-ai-zhipu:glm-5.2'),
      candidate('Z-AI-Zhipu:glm-5.1'),
    ],
    [
      candidate('z-ai-zhipu:glm-5.2'),
      candidate('lab:glm-5.1'),
    ],
  ),
  ['z-ai-zhipu:glm-5', 'z-ai-zhipu:glm-5.1'],
  'Active older same-provider GLM candidates should be reported when GLM-5.2 is configured on that provider',
);
assert.deepEqual(
  activeOlderSameProviderGlmCandidateIds(
    [
      candidate('z-ai-zhipu:glm-5.1'),
      candidate('lab:glm-5.1'),
    ],
    [
      candidate('lab:glm-5.2'),
      candidate('z-ai-zhipu:glm-5.1'),
    ],
  ),
  ['lab:glm-5.1'],
  'Active older GLM candidates should only be reported for the provider namespace that has GLM-5.2 configured',
);
assert.deepEqual(
  activeOlderSameProviderGlmCandidateIds(
    [
      candidate('z-ai-zhipu:glm-5.1'),
      candidate('minimax:MiniMax-M3'),
    ],
    [
      candidate('z-ai-zhipu:glm-5.1'),
      candidate('minimax:MiniMax-M3'),
    ],
  ),
  [],
  'Active older GLM candidates should stay quiet when no same-provider GLM-5.2 is configured',
);
const duplicateCaseCandidates = [
  candidateWithCard('Z-AI-Zhipu : glm-5.2', 'spaced GLM-5.2 card'),
  candidateWithCard('z-ai-zhipu:glm-5.1', 'duplicate first'),
  candidateWithCard('Z-AI-Zhipu:glm-5.1', 'duplicate second'),
  candidateWithCard('z-ai-zhipu:glm-5', 'base glm-5 card'),
  candidateWithCard('minimax:MiniMax-M3', 'M3 card'),
];
assert.deepEqual(
  filterAutoGeneratedGlmRouterCandidates(
    duplicateCaseCandidates,
    summarizeAutoGeneratedGlmRouterCandidatePreference(duplicateCaseCandidates),
  ).map((item) => item.modelId),
  filterAutoGeneratedGlmRouterCandidates(duplicateCaseCandidates).map((item) => item.modelId),
  'Filtering with a precomputed GLM preference summary should match default filtering',
);
assert.deepEqual(
  formatGlmSuppressedCandidateList([]),
  {
    visibleText: '',
    accessibilityText: '',
    fullText: '',
    hiddenCount: 0,
  },
  'empty suppressed GLM candidate lists should not render placeholder text',
);
assert.deepEqual(
  formatGlmSuppressedCandidateList([
    'z-ai-zhipu:glm-5.1-zeta',
    'z-ai-zhipu:glm-5.1-alpha',
    'z-ai-zhipu:glm-5.1-beta',
    'z-ai-zhipu:glm-5.1-gamma',
  ]),
  {
    visibleText: 'z-ai-zhipu:glm-5.1-alpha, z-ai-zhipu:glm-5.1-beta, z-ai-zhipu:glm-5.1-gamma, +1 more',
    accessibilityText: 'z-ai-zhipu:glm-5.1-alpha, z-ai-zhipu:glm-5.1-beta, z-ai-zhipu:glm-5.1-gamma, z-ai-zhipu:glm-5.1-zeta',
    fullText: 'z-ai-zhipu:glm-5.1-alpha, z-ai-zhipu:glm-5.1-beta, z-ai-zhipu:glm-5.1-gamma, z-ai-zhipu:glm-5.1-zeta',
    hiddenCount: 1,
  },
  'suppressed GLM candidate formatter should show a stable sorted preview while keeping full accessibility text',
);
assert.equal(
  pickPreferredGlm52RouterCandidate([
    candidate('z-ai-zhipu:glm-5.1'),
    candidate('z-ai-zhipu:glm-5.2'),
    candidate('minimax:MiniMax-M3'),
  ]),
  'z-ai-zhipu:glm-5.2',
  'Settings should prefer the configured GLM-5.2 candidate when it is present but not first',
);
assert.equal(
  pickPreferredGlm52RouterCandidate([
    candidate('z-ai-zhipu:glm-5.1'),
    candidate('minimax:MiniMax-M3'),
  ]),
  'z-ai-zhipu:glm-5.1',
  'Settings should fall back to the first configured candidate when GLM-5.2 is unavailable',
);

const withoutGlm52 = filterAutoGeneratedGlmRouterCandidates([
  candidate('z-ai-zhipu:glm-5.1'),
  candidate('minimax:MiniMax-M3'),
]);
assert.deepEqual(
  withoutGlm52.map((item) => item.modelId),
  ['z-ai-zhipu:glm-5.1', 'minimax:MiniMax-M3'],
  'Older GLM-5 should remain an auto-router candidate when GLM-5.2 is unavailable',
);

const differentProviderGlm52 = filterAutoGeneratedGlmRouterCandidates([
  candidate('z-ai-zhipu:glm-5.1'),
  candidate('lab:glm-5.2'),
]);
assert.deepEqual(
  differentProviderGlm52.map((item) => item.modelId),
  ['z-ai-zhipu:glm-5.1', 'lab:glm-5.2'],
  'Older GLM-5 should not be suppressed by GLM-5.2 on a different provider namespace',
);

const settingsSource = readFileSync('src/components/SettingsModal.tsx', 'utf8');
assert.ok(
  settingsSource.includes('filterAutoGeneratedGlmRouterCandidates(candidates, glmPreference)'),
  'Settings auto-router scan should reuse the GLM preference summary when filtering auto-generated candidates',
);
assert.ok(
  settingsSource.includes('summarizeAutoGeneratedGlmRouterCandidatePreference(candidates)'),
  'Settings auto-router scan should compute a GLM preference summary from raw configured candidates before filtering',
);
assert.ok(
  settingsSource.includes('glm52PreferenceNoticeLabel()'),
  'Settings auto-router UI should explain when older GLM configured candidates were suppressed by GLM-5.2 preference',
);
assert.ok(
  settingsSource.indexOf('{configuredGlmPreference.suppressedCount > 0 && (') < settingsSource.indexOf('{arEnabled && ('),
  'Settings auto-router UI should show the GLM-5.2 preference notice even before Auto-Router is enabled',
);
assert.ok(
  settingsSource.includes('configuredGlmPreference.suppressedCount'),
  'Settings auto-router UI should expose the suppressed GLM candidate count',
);
assert.ok(
  settingsSource.includes('activeOlderSameProviderGlmCandidateIdsForRouter(arCandidates, configuredCandidates)'),
  'Settings auto-router UI should compute active older same-provider GLM drift without changing active manual candidates',
);
assert.ok(
  settingsSource.includes('Active older GLM still routed'),
  'Settings auto-router UI should call out active older GLM candidates when GLM-5.2 is configured',
);
assert.ok(
  settingsSource.includes('glmActiveOlderRoutingWarning()'),
  'Settings auto-router UI should guide the user without silently mutating manual GLM candidates',
);
assert.ok(
  settingsSource.includes('glmActiveOlderRoutingWarning()'),
  'Settings auto-router UI should make clear that the older-GLM warning is informational',
);
assert.ok(
  settingsSource.includes('const glmPatienceStatusParts = [')
    && settingsSource.includes('glmPatienceCandidateStatusLabel(')
    && settingsSource.includes('activeOlderGlmCandidateIds.length > 0')
    && settingsSource.includes("aria-label={glmPatienceStatusParts.join('. ')}"),
  'Settings GLM patience card aria-label should be built from the same candidate-count and active older-GLM drift messages as the visible card',
);
assert.ok(
  settingsSource.includes('Preferred GLM-5.2 provider') && settingsSource.includes('configuredGlmPreference.preferredProviderIds.join'),
  'Settings auto-router UI should expose the provider ids that triggered the GLM-5.2 preference',
);
assert.ok(
  settingsSource.includes('configuredGlmSuppressedCandidates.visibleText'),
  'Settings auto-router UI should render the compact GLM suppression preview',
);
assert.ok(
  settingsSource.includes('configuredGlmSuppressedCandidates.accessibilityText'),
  'Settings auto-router status aria-label should keep the complete suppressed GLM candidate list',
);
assert.ok(
  settingsSource.includes('const syncPreferredGlmCandidateModelId = updated.find((candidate) => isGlm52ModelId(candidate.modelId))?.modelId || \'\';'),
  'Settings configured-model sync should use GLM-5.2 as a default fallback only when GLM-5.2 is present',
);
assert.ok(
  settingsSource.includes('resolveRouterSelection(arDefaultModel, updated, syncPreferredGlmCandidateModelId || nextClassifier)'),
  'Settings configured-model sync should prefer GLM-5.2 for invalid default selections before falling back to classifier',
);
assert.ok(
  !settingsSource.includes('filterAutoGeneratedGlmRouterCandidates([...existing, ...configured])'),
  'Manual or existing router candidates should not be suppressed by the GLM preference filter',
);
for (const localSettingsGlmLiteral of [
  'Give GLM the extended wait before treating slow responses as failure.',
  'GLM is a slower specialist for deep planning, review, and reasoning. Keep it in the patient lane so routing gives it time to finish careful work before fallback.',
  'This does not change active routing. Review manual candidates or restore recommended defaults if you want GLM-5.2 to take over on that provider.',
  'GLM-5.2 preference suppressed',
  '<span>GLM-5.2 preference</span>',
  'because GLM-5.2 is configured on the same provider',
]) {
  assert.ok(
    !settingsSource.includes(localSettingsGlmLiteral),
    `Settings GLM preference cards should not own shared copy locally: ${localSettingsGlmLiteral}`,
  );
}

console.log('GLM router candidate preference checks passed.');
