import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';

const electronMain = readFileSync('electron/main.cjs', 'utf-8');
const serverIndex = readFileSync('server/index.ts', 'utf-8');
const startScript = readFileSync('scripts/start.mjs', 'utf-8');
const eslintConfig = readFileSync('eslint.config.js', 'utf-8');
const router = readFileSync('server/router.ts', 'utf-8');
const routingPane = readFileSync('src/components/RoutingLearningPane.tsx', 'utf-8');
const settingsModal = readFileSync('src/components/SettingsModal.tsx', 'utf-8');
const assistantSettingsPanes = readFileSync('src/components/settings/AssistantSettingsPanes.tsx', 'utf-8');
const infoSettingsPanes = readFileSync('src/components/settings/InfoSettingsPanes.tsx', 'utf-8');
const mcpSettingsPanes = readFileSync('src/components/settings/McpSettingsPanes.tsx', 'utf-8');
const onboardingSettingsPanes = readFileSync('src/components/settings/OnboardingSettingsPanes.tsx', 'utf-8');
const preferenceSettingsPanes = readFileSync('src/components/settings/PreferenceSettingsPanes.tsx', 'utf-8');
const autoRouter = readFileSync('server/autoRouter.ts', 'utf-8');
const runtimeConfig = readFileSync('shared/runtimeConfig.cjs', 'utf-8');
const credentialVault = readFileSync('server/credentialVault.ts', 'utf-8');
const remoteApiAccess = readFileSync('server/remoteApiAccess.ts', 'utf-8');
const requestSchemas = readFileSync('server/requestSchemas.ts', 'utf-8');
const routeSupport = readFileSync('server/routeSupport.ts', 'utf-8');
const chatStreamSupport = readFileSync('server/chatStreamSupport.ts', 'utf-8');
const actionApprovals = readFileSync('server/actionApprovals.ts', 'utf-8');
const agentRoutes = readFileSync('server/routes/agentRoutes.ts', 'utf-8');
const approvalRoutes = readFileSync('server/routes/approvalRoutes.ts', 'utf-8');
const terminalRoutes = readFileSync('server/routes/terminalRoutes.ts', 'utf-8');
const appInfoRoutes = readFileSync('server/routes/appInfoRoutes.ts', 'utf-8');
const benchExecutionRoutes = readFileSync('server/routes/benchExecutionRoutes.ts', 'utf-8');
const benchRoutes = readFileSync('server/routes/benchRoutes.ts', 'utf-8');
const browserRoutes = readFileSync('server/routes/browserRoutes.ts', 'utf-8');
const chatCompareRoutes = readFileSync('server/routes/chatCompareRoutes.ts', 'utf-8');
const chatMessageRoutes = readFileSync('server/routes/chatMessageRoutes.ts', 'utf-8');
const evalRunRoutes = readFileSync('server/routes/evalRunRoutes.ts', 'utf-8');
const configRoutes = readFileSync('server/routes/configRoutes.ts', 'utf-8');
const filesystemRoutes = readFileSync('server/routes/filesystemRoutes.ts', 'utf-8');
const providerRoutes = readFileSync('server/routes/providerRoutes.ts', 'utf-8');
const gitRoutes = readFileSync('server/routes/gitRoutes.ts', 'utf-8');
const labUtilityRoutes = readFileSync('server/routes/labUtilityRoutes.ts', 'utf-8');
const opsRoutes = readFileSync('server/routes/opsRoutes.ts', 'utf-8');
const patchProposalRoutes = readFileSync('server/routes/patchProposalRoutes.ts', 'utf-8');
const projectMemoryRoutes = readFileSync('server/routes/projectMemoryRoutes.ts', 'utf-8');
const projectRepoRoutes = readFileSync('server/routes/projectRepoRoutes.ts', 'utf-8');
const routerRoutes = readFileSync('server/routes/routerRoutes.ts', 'utf-8');
const sessionRoutes = readFileSync('server/routes/sessionRoutes.ts', 'utf-8');
const systemRoutes = readFileSync('server/routes/systemRoutes.ts', 'utf-8');
const taskRoutes = readFileSync('server/routes/taskRoutes.ts', 'utf-8');
const testRoutes = readFileSync('server/routes/testRoutes.ts', 'utf-8');
const usageRoutes = readFileSync('server/routes/usageRoutes.ts', 'utf-8');
const desktopDecision = readFileSync('docs/DESKTOP_SURFACE_DECISION.md', 'utf-8');
const releaseChecklist = readFileSync('docs/RELEASE_CHECKLIST.md', 'utf-8');
const readme = readFileSync('README.md', 'utf-8');
const ciWorkflow = readFileSync('.github/workflows/ci.yml', 'utf-8');

assert.match(router, /asksAdvisoryChange/, 'router should distinguish advisory change suggestions from execute requests');
assert.match(router, /else if \(asksReview && !simpleQuestion\) mode = 'investigate';\s+else if \(asksPlan\) mode = 'plan';/s, 'review/security intent should beat architecture/planning nouns');

assert.match(electronMain, /setWindowOpenHandler/, 'Electron should block new-window navigation');
assert.match(electronMain, /will-navigate/, 'Electron should block top-level external navigation');
assert.match(electronMain, /Content-Security-Policy/, 'Electron should inject a CSP for app origins');
assert.match(electronMain, /screen\.getDisplayMatching\(mainWindow\.getBounds\(\)\)/, 'snap zones should use the display containing the current window');
assert.match(electronMain, /http:\/\/127\.0\.0\.1:\$\{VITE_PORT\}/, 'dev renderer should load loopback by address');
assert.match(electronMain, /http:\/\/127\.0\.0\.1:\$\{SERVER_PORT\}/, 'packaged renderer should load loopback by address');
assert.match(electronMain, /getRuntimeConfig/, 'Electron should use the shared runtime port/origin config');
assert.match(electronMain, /path: '\/api\/ready'/, 'Packaged Electron should use the dedicated readiness endpoint');
assert.match(electronMain, /x-openharness-electron-handshake/, 'Packaged Electron readiness should use the per-launch handshake');

assert.match(serverIndex, /OPENHARNESS_AUTO_START_DOCKER_MCP !== '1'/, 'Docker MCP startup should require explicit opt-in');
assert.match(serverIndex, /Docker MCP auto-start disabled; use MCP lifecycle controls to start it\./, 'Docker MCP disabled startup should be visible in logs');
assert.match(serverIndex, /mcpManager\.startWatchdog\(30_000\)/, 'MCP watchdog should still start even when Docker MCP auto-start is disabled');
assert.match(serverIndex, /OPENHARNESS_ENABLE_REMOTE_API === '1'/, 'Remote API exposure should require explicit opt-in');
assert.match(serverIndex, /OPENHARNESS_REMOTE_API_TOKEN/, 'Remote API exposure should require a token');
assert.match(serverIndex, /express\.json\(\{ limit: '5mb' \}\)/, 'Global JSON body limit should not stay at the old broad 50mb limit');
assert.match(serverIndex, /createRemoteApiGuard\(\{ enabled: REMOTE_API_ENABLED, token: REMOTE_API_TOKEN \}\)/, 'Server should use extracted remote API access guard');
assert.match(systemRoutes, /\/api\/ready/, 'Server should expose a dedicated readiness endpoint from the system route module');
assert.match(systemRoutes, /Invalid Electron readiness handshake/, 'Readiness should reject invalid packaged Electron handshakes');
assert.match(serverIndex, /registerAgentRoutes\(app/, 'Agent profile and background-agent routes should be registered from a route module');
assert.match(serverIndex, /registerApprovalRoutes\(app/, 'Approval transaction routes should be registered from a route module');
assert.match(serverIndex, /ensureAskBeforeWriteApproval/, 'Server should enforce ask-before-write approval transactions');
assert.match(serverIndex, /requires an explicit approval transaction in ask-before-write mode/, 'Automatic model write/command tools should be blocked in ask-before-write mode');
assert.match(serverIndex, /registerTerminalRoutes\(app/, 'Terminal route family should be registered from a route module');
assert.match(serverIndex, /registerAppInfoRoutes\(app, \{\s+ensureLocalMutationWithControl,\s+\}\)/, 'Personalization mutation routes should be registered with local mutation control');
assert.match(serverIndex, /registerBenchExecutionRoutes\(app/, 'Bench execution route should be registered from a route module');
assert.match(serverIndex, /registerBenchRoutes\(app/, 'Bench report routes should be registered from a route module');
assert.match(serverIndex, /registerBrowserRoutes\(app\)/, 'Browser route family should be registered from a route module');
assert.match(serverIndex, /registerChatCompareRoutes\(app/, 'Chat comparison route should be registered from a route module');
assert.match(serverIndex, /registerChatMessageRoutes\(app/, 'Main chat message route should be registered from a route module');
assert.match(serverIndex, /registerEvalRunRoutes\(app/, 'Eval execution route should be registered from a route module');
assert.match(serverIndex, /registerConfigRoutes\(app/, 'Config route family should be registered from a route module');
assert.match(serverIndex, /registerFilesystemRoutes\(app/, 'Filesystem route family should be registered from a route module');
assert.match(serverIndex, /registerProviderRoutes\(app/, 'Provider route family should be registered from a route module');
assert.match(serverIndex, /registerGitRoutes\(app/, 'Git, ship readiness, and patch apply routes should be registered from a route module');
assert.match(serverIndex, /registerLabUtilityRoutes\(app/, 'Eval report, capability, prompt plugin, debug bundle, and prompt helper routes should be registered from a route module');
assert.match(serverIndex, /registerOpsRoutes\(app/, 'Checkpoint, worktree, protected-path, process, and safety routes should be registered from a route module');
assert.match(serverIndex, /registerPatchProposalRoutes\(app/, 'Patch proposal route family should be registered from a route module');
assert.match(serverIndex, /registerProjectMemoryRoutes\(app/, 'Project memory route family should be registered from a route module');
assert.match(serverIndex, /registerProjectRepoRoutes\(app/, 'Project profile and repo-map route family should be registered from a route module');
assert.match(serverIndex, /registerRouterRoutes\(app/, 'Router and router-learning route family should be registered from a route module');
assert.match(serverIndex, /registerSessionRoutes\(app/, 'Session route family should be registered from a route module');
assert.match(serverIndex, /registerSystemRoutes\(app/, 'Readiness, native dialog, and cost-estimate routes should be registered from a route module');
assert.match(serverIndex, /registerTaskRoutes\(app/, 'Harness task and task-suite routes should be registered from a route module');
assert.match(serverIndex, /registerTestRoutes\(app/, 'Test harness routes should be registered from a route module');
assert.match(serverIndex, /registerUsageRoutes\(app/, 'Usage tracking routes should be registered from a route module');
assert.match(chatMessageRoutes, /chatMessageSchema = objectSchema/, 'Main chat message route should use a runtime payload schema');
assert.match(chatMessageRoutes, /parseBody\(req, res, chatMessageSchema\)/, 'Main chat message route should reject invalid request bodies before streaming');
assert.match(chatMessageRoutes, /app\.post\('\/api\/sessions\/:id\/messages'/, 'Main chat message route should live in its route module');
assert.doesNotMatch(serverIndex, /app\.(get|post|put|delete|patch)\('\/api/, 'API route declarations should not remain inline in the server entrypoint');
assert.match(chatStreamSupport, /export function openHarnessWorkspaceMismatch/, 'Main chat workspace guard should live outside the server entrypoint');
assert.match(chatStreamSupport, /export function emitVisibleRunActivity/, 'Visible chat run activity formatting should live outside the server entrypoint');
assert.match(chatStreamSupport, /export function compactTracePreview/, 'Trace preview compaction should live outside the server entrypoint');
assert.match(chatStreamSupport, /export function writeSSE/, 'SSE event writer should live outside the server entrypoint');
assert.match(chatStreamSupport, /export async function streamTextSSE/, 'Chunked SSE text streaming should live outside the server entrypoint');
assert.match(chatStreamSupport, /export function maybeEmitThinkingSSE/, 'Throttled thinking SSE helper should live outside the server entrypoint');
assert.doesNotMatch(serverIndex, /function writeSSE/, 'SSE event writer should not remain inline in the server entrypoint');
assert.doesNotMatch(serverIndex, /function maybeEmitThinkingSSE/, 'Thinking SSE helper should not remain inline in the server entrypoint');
assert.doesNotMatch(serverIndex, /function thinkingMessageForRunStep/, 'Visible run activity message formatting should not remain inline in the server entrypoint');
assert.doesNotMatch(serverIndex, /function openHarnessWorkspaceMismatch/, 'Main chat workspace guard should not remain inline in the server entrypoint');

assert.match(startScript, /getRuntimeConfig/, 'Start script should use the shared runtime port/origin config');
assert.match(startScript, /VITE_OPENHARNESS_SERVER_PORT/, 'Start script should pass server port to Vite for the browser API helper');
assert.match(runtimeConfig, /function getRuntimeConfig/, 'Shared runtime config should centralize runtime port and origin calculation');
assert.match(runtimeConfig, /allowedAppOrigins/, 'Shared runtime config should centralize allowed app origins');

assert.match(eslintConfig, /files: \['src\/\*\*\/\*\.\{ts,tsx\}'\][\s\S]*globals: \{ \.\.\.globals\.browser \}/, 'ESLint should scope browser globals to src files');
assert.match(eslintConfig, /files: \['server\/\*\*\/\*\.ts', 'scripts\/\*\*\/\*\.ts', 'vite\.config\.ts'\][\s\S]*globals: \{ \.\.\.globals\.node \}/, 'ESLint should scope Node globals to server, scripts, and Vite config');
assert.match(eslintConfig, /files: \['shared\/\*\*\/\*\.cjs', 'eslint\.config\.js'\]/, 'ESLint should lint shared Node JS config under Node globals');

assert.match(desktopDecision, /Electron is the canonical OpenHarness desktop shell for V1 releases\./, 'Desktop decision should name Electron as the canonical V1 shell');
assert.match(desktopDecision, /`OpenHarnessApp\/` is retained as a Swift\/WKWebView native-shell prototype/, 'Desktop decision should keep Swift shell non-shipping by default');
assert.match(releaseChecklist, /Electron desktop shell \/ packaging changes/, 'Release checklist should track Electron desktop changes separately');
assert.match(releaseChecklist, /Swift prototype \(`OpenHarnessApp`\) changes/, 'Release checklist should track Swift prototype changes separately');
assert.match(releaseChecklist, /Confirm the Swift prototype is still non-shipping/, 'Swift changes should require a non-shipping confirmation or reactivation plan');
assert.match(readme, /Electron is the V1 desktop release surface/, 'README should point users to the canonical Electron desktop shell');

assert.match(credentialVault, /credentials\.enc\.json/, 'Credential vault should store secrets outside config.json');
assert.match(credentialVault, /scrubStoredConfigCredentials/, 'Credential vault should expose config scrubbing');
assert.match(credentialVault, /hydrateStoredConfigCredentials/, 'Credential vault should hydrate runtime config secrets');
assert.match(serverIndex + readFileSync('server/config.ts', 'utf-8'), /hasInlineConfigCredentials[\s\S]*saveConfig\(finalConfig\)/, 'Loading legacy inline credentials should trigger scrubbed config migration');
assert.match(remoteApiAccess, /x-openharness-api-token/, 'Remote API token guard should remain present after extraction');
assert.match(remoteApiAccess, /export function createRemoteApiGuard/, 'Remote API access guard should live outside the server entrypoint');
assert.match(remoteApiAccess, /export function isLoopbackAddress/, 'Loopback address classification should live outside the server entrypoint');
assert.match(remoteApiAccess, /export function browserMutationOriginAllowed/, 'Browser-origin mutation checks should live outside the server entrypoint');
assert.match(serverIndex, /browserMutationOriginAllowed\(req, allowedOrigins\)/, 'Local mutation control should reject cross-site browser-origin requests before loopback shortcuts');
assert.match(requestSchemas, /export function objectSchema/, 'Runtime request schema helper should be available for API payloads');
assert.match(requestSchemas, /export function parseBody/, 'Runtime request schema helper should reject invalid request bodies');
assert.match(requestSchemas, /export function requiredNonBlankString/, 'Runtime request schema helper should validate non-blank strings without trimming payloads');
assert.match(requestSchemas, /export function requiredStringArray/, 'Runtime request schema helper should validate required string arrays');
assert.match(requestSchemas, /export function optionalBoolean/, 'Runtime request schema helper should validate optional booleans');
assert.match(requestSchemas, /export function optionalNumber/, 'Runtime request schema helper should validate optional numbers');
assert.match(requestSchemas, /export function optionalInteger/, 'Runtime request schema helper should validate optional integers');
assert.match(requestSchemas, /export function optionalRecord/, 'Runtime request schema helper should validate optional object payloads');
assert.match(routeSupport, /export function sendRouteError/, 'Route error mapping should be centralized');
assert.match(routeSupport, /export function auditRouteMutation/, 'Route mutation audit logging should be centralized');
assert.match(actionApprovals, /export function createApprovalTransaction/, 'Approval transactions should be explicit objects');
assert.match(actionApprovals, /fingerprint/, 'Approval transactions should bind approval to an action fingerprint');
assert.match(actionApprovals, /approval\.status = 'consumed'/, 'Approval transactions should be single-use');
assert.match(agentRoutes, /export function registerAgentRoutes/, 'Agent routes should live outside the server entrypoint');
assert.match(agentRoutes, /\/api\/agents\/profiles/, 'Agent profile routes should live in the agent route module');
assert.match(agentRoutes, /\/api\/agents\/background/, 'Background agent routes should live in the agent route module');
assert.match(agentRoutes, /startBackgroundAgent/, 'Background agent start behavior should remain in the extracted route');
assert.match(agentRoutes, /ensureWorkspaceReadAllowed/, 'Background agent routes should preserve workspace read validation after extraction');
assert.match(approvalRoutes, /export function registerApprovalRoutes/, 'Approval routes should live outside the server entrypoint');
assert.match(approvalRoutes, /\/api\/approvals/, 'Approval listing route should live in the approval route module');
assert.match(approvalRoutes, /\/api\/approvals\/:id\/approve/, 'Approval approve route should live in the approval route module');
assert.match(approvalRoutes, /\/api\/approvals\/:id\/reject/, 'Approval reject route should live in the approval route module');
assert.match(approvalRoutes, /ensureLocalControl/, 'Approval routes should preserve local-control checks after extraction');
assert.match(terminalRoutes, /export function registerTerminalRoutes/, 'Terminal routes should live outside the server entrypoint');
assert.match(terminalRoutes, /ensureAskBeforeWriteApproval/, 'Extracted terminal routes should keep ask-before-write approval enforcement');
assert.match(appInfoRoutes, /export function registerAppInfoRoutes/, 'App info routes should live outside the server entrypoint');
assert.match(appInfoRoutes, /\/api\/personalization/, 'Personalization routes should live in the app info route module');
assert.match(appInfoRoutes, /app\.put\('\/api\/personalization'[\s\S]*ensureLocalMutationWithControl/, 'Personalization PUT should require local mutation control');
assert.match(appInfoRoutes, /app\.delete\('\/api\/personalization'[\s\S]*ensureLocalMutationWithControl/, 'Personalization DELETE should require local mutation control');
assert.match(appInfoRoutes, /\/api\/release-notes/, 'Release notes route should live in the app info route module');
assert.match(appInfoRoutes, /\/api\/crash-reports/, 'Crash report routes should live in the app info route module');
assert.match(benchExecutionRoutes, /export function registerBenchExecutionRoutes/, 'Bench execution route should live outside the server entrypoint');
assert.match(benchExecutionRoutes, /benchRunSchema = objectSchema/, 'Bench execution route should use a runtime payload schema');
assert.match(benchExecutionRoutes, /requiredStringArray/, 'Bench execution route should validate task and model arrays');
assert.match(benchExecutionRoutes, /\/api\/bench\/run/, 'Bench execution route should live in the bench execution route module');
assert.match(benchExecutionRoutes, /runOrchestratorPipeline/, 'Bench execution route should preserve orchestrated bench execution');
assert.match(benchExecutionRoutes, /invokeMCPTool/, 'Bench execution route should preserve MCP tool invocation behavior');
assert.match(benchExecutionRoutes, /streamModel/, 'Bench execution route should preserve direct model streaming behavior');
assert.match(benchExecutionRoutes, /buildBenchTraceProof/, 'Bench execution route should preserve trace proof generation');
assert.match(benchExecutionRoutes, /validateExpectedPathChanges/, 'Bench execution route should preserve expected path validation');
assert.match(benchExecutionRoutes, /recordUsage/, 'Bench execution route should preserve usage recording');
assert.doesNotMatch(serverIndex, /app\.post\('\/api\/bench\/run/, 'Bench execution route should not remain inline in the server entrypoint');
assert.match(benchRoutes, /export function registerBenchRoutes/, 'Bench report routes should live outside the server entrypoint');
assert.match(benchRoutes, /\/api\/bench\/runs/, 'Bench run report routes should live in the bench route module');
assert.match(benchRoutes, /proof-review/, 'Bench proof-review route should live in the bench route module');
assert.match(benchRoutes, /exportBenchRunCSV/, 'Bench CSV export should remain in the extracted route');
assert.match(benchRoutes, /ensureLocalMutationWithControl/, 'Bench proof-review mutation should preserve local mutation checks');
assert.doesNotMatch(serverIndex, /app\.(get|post)\('\/api\/bench\/runs/, 'Bench report routes should not remain inline in the server entrypoint');
assert.match(browserRoutes, /export function registerBrowserRoutes/, 'Browser routes should live outside the server entrypoint');
assert.match(browserRoutes, /sendRouteError/, 'Browser route failures should use centralized error mapping');
assert.match(browserRoutes, /\/api\/browser\/preview/, 'Browser preview route should live in the browser route module');
assert.match(browserRoutes, /\/api\/browser\/deep/, 'Deep browser route should live in the browser route module');
assert.match(browserRoutes, /\/api\/browser\/console-log/, 'Browser console relay routes should live in the browser route module');
assert.match(chatCompareRoutes, /export function registerChatCompareRoutes/, 'Chat comparison route should live outside the server entrypoint');
assert.match(chatCompareRoutes, /chatCompareSchema = objectSchema/, 'Chat comparison route should use a runtime payload schema');
assert.match(chatCompareRoutes, /optionalInteger/, 'Chat comparison messageIndex should be integer-validated');
assert.match(chatCompareRoutes, /\/api\/chat\/compare/, 'Chat comparison route should live in the chat compare route module');
assert.match(chatCompareRoutes, /resolveProviderForModel/, 'Chat comparison route should preserve provider resolution behavior');
assert.match(chatCompareRoutes, /streamModel/, 'Chat comparison route should preserve model streaming behavior');
assert.match(chatCompareRoutes, /redactOutputText/, 'Chat comparison route should preserve response redaction');
assert.doesNotMatch(serverIndex, /app\.post\('\/api\/chat\/compare/, 'Chat comparison route should not remain inline in the server entrypoint');
assert.match(evalRunRoutes, /export function registerEvalRunRoutes/, 'Eval execution route should live outside the server entrypoint');
assert.match(evalRunRoutes, /evalRunSchema = objectSchema/, 'Eval execution route should use a runtime payload schema');
assert.match(evalRunRoutes, /requiredStringArray/, 'Eval execution route should validate prompt and model arrays');
assert.match(evalRunRoutes, /optionalRecord/, 'Eval execution route should validate pack context as an object');
assert.match(evalRunRoutes, /\/api\/evals\/run/, 'Eval execution route should live in the eval run route module');
assert.match(evalRunRoutes, /resolveProviderForModel/, 'Eval execution route should preserve provider resolution behavior');
assert.match(evalRunRoutes, /streamModel/, 'Eval execution route should preserve model streaming behavior');
assert.match(evalRunRoutes, /disposeEphemeralSession/, 'Eval execution route should clean up ephemeral sessions');
assert.match(evalRunRoutes, /recordUsage/, 'Eval execution route should preserve usage recording');
assert.match(evalRunRoutes, /promptStrategyTraceForModel/, 'Eval execution route should preserve prompt strategy trace behavior');
assert.doesNotMatch(serverIndex, /app\.post\('\/api\/evals\/run/, 'Eval execution route should not remain inline in the server entrypoint');
assert.match(configRoutes, /export function registerConfigRoutes/, 'Config routes should live outside the server entrypoint');
assert.match(configRoutes, /\/api\/config/, 'Config read and update routes should live in the config route module');
assert.match(configRoutes, /apiKey: p\.apiKey \? '••••' \+ p\.apiKey\.slice\(-4\)/, 'Config API responses should keep masking provider API keys');
assert.match(configRoutes, /maskProviderOAuth/, 'Config API responses should keep masking provider OAuth secrets');
assert.match(configRoutes, /isTrustMode/, 'Config updates should validate trust-mode values');
assert.match(configRoutes, /normalizeTrustMode/, 'Config updates should normalize trust-mode values');
assert.match(configRoutes, /configureAutoRouter/, 'Config updates should preserve auto-router configuration behavior');
assert.match(configRoutes, /saveConfig\(appConfig\)/, 'Config updates should persist through the config save path');
assert.match(configRoutes, /x-openharness-electron-handshake/, 'Config responses should preserve the Electron handshake acknowledgement header');
assert.match(filesystemRoutes, /export function registerFilesystemRoutes/, 'Filesystem routes should live outside the server entrypoint');
assert.match(filesystemRoutes, /\/api\/fs\/list/, 'Filesystem list route should live in the filesystem route module');
assert.match(filesystemRoutes, /\/api\/fs\/read/, 'Filesystem read route should live in the filesystem route module');
assert.match(filesystemRoutes, /isReadPathAllowed/, 'Filesystem routes should preserve trust-mode read checks after extraction');
assert.match(filesystemRoutes, /trustedWorkspaceFromRequest/, 'Filesystem routes should preserve trusted-workspace read context after extraction');
assert.match(providerRoutes, /export function registerProviderRoutes/, 'Provider routes should live outside the server entrypoint');
assert.match(providerRoutes, /sendRouteError/, 'Provider route failures should use centralized error mapping');
assert.match(providerRoutes, /auditRouteMutation/, 'Provider route mutations should use centralized audit logging');
assert.match(providerRoutes, /providerBatchSchema = objectSchema/, 'Provider batch route should use a runtime payload schema');
assert.match(providerRoutes, /createProviderSchema = objectSchema/, 'Provider create route should use a runtime payload schema');
assert.match(providerRoutes, /updateProviderSchema = objectSchema/, 'Provider update route should use a runtime payload schema');
assert.match(providerRoutes, /\/api\/providers\/rate-limits\/status/, 'Provider rate-limit route should live in the provider route module');
assert.match(providerRoutes, /\/api\/providers\/:id\/oauth\/status/, 'Provider OAuth route should live in the provider route module');
assert.match(providerRoutes, /\/api\/models\/metadata\/refresh/, 'Model metadata refresh route should live in the provider route module');
assert.match(providerRoutes, /\/api\/providers\/:id\/health\/probe/, 'Provider health route should live in the provider route module');
assert.match(gitRoutes, /export function registerGitRoutes/, 'Git routes should live outside the server entrypoint');
assert.match(gitRoutes, /sendRouteError/, 'Git route failures should use centralized error mapping');
assert.match(gitRoutes, /gitPathsMutationSchema = objectSchema/, 'Git path mutation routes should use runtime payload schemas');
assert.match(gitRoutes, /patchApplySchema = objectSchema/, 'Patch apply route should use a runtime payload schema');
assert.match(gitRoutes, /\/api\/git\/stage/, 'Git stage route should live in the git route module');
assert.match(gitRoutes, /\/api\/ship\/readiness/, 'Ship readiness route should live in the git route module');
assert.match(gitRoutes, /\/api\/patches\/apply/, 'Patch apply route should live in the git route module');
assert.match(labUtilityRoutes, /export function registerLabUtilityRoutes/, 'Lab utility routes should live outside the server entrypoint');
assert.match(labUtilityRoutes, /\/api\/evals\/prompts/, 'Eval prompt route should live in the lab utility route module');
assert.match(labUtilityRoutes, /\/api\/evals\/reports/, 'Eval report routes should live in the lab utility route module');
assert.match(labUtilityRoutes, /\/api\/capabilities/, 'Capability routes should live in the lab utility route module');
assert.match(labUtilityRoutes, /\/api\/prompt-plugins/, 'Prompt plugin routes should live in the lab utility route module');
assert.match(labUtilityRoutes, /debug-bundle/, 'Debug bundle routes should live in the lab utility route module');
assert.match(labUtilityRoutes, /\/api\/prompt\/redact/, 'Prompt redaction route should live in the lab utility route module');
assert.match(labUtilityRoutes, /\/api\/prompt\/estimate/, 'Prompt estimation route should live in the lab utility route module');
assert.match(labUtilityRoutes, /ensureLocalMutationWithControl/, 'Extracted lab utility mutations should preserve local mutation checks');
assert.match(labUtilityRoutes, /ensureExplicitApproval/, 'Prompt skill import should require explicit source-read approval outside the active workspace');
assert.match(labUtilityRoutes, /isPathWithin\(resolvedSource, targetWorkspace\.dir\)/, 'Prompt skill import should allow unapproved reads only inside the active workspace');
assert.match(labUtilityRoutes, /ensureKnownWorkspace/, 'Extracted lab utility routes should preserve workspace checks');
assert.doesNotMatch(serverIndex, /app\.(get|post|put)\('\/api\/(evals\/prompts|prompt-strategies|evals\/reports|evals\/recommendations|capabilities|prompt-plugins|prompt\/redact|prompt\/estimate)/, 'Lab utility routes should not remain inline in the server entrypoint');
assert.doesNotMatch(serverIndex, /app\.get\('\/api\/(sessions\/:sessionId\/messages\/:messageId|runs\/:runId)\/debug-bundle/, 'Debug bundle routes should not remain inline in the server entrypoint');
assert.match(opsRoutes, /export function registerOpsRoutes/, 'Ops routes should live outside the server entrypoint');
assert.match(opsRoutes, /checkpointCreateSchema = objectSchema/, 'Checkpoint create route should use a runtime payload schema');
assert.match(opsRoutes, /worktreeCreateSchema = objectSchema/, 'Worktree create route should use a runtime payload schema');
assert.match(opsRoutes, /secretScanFilesSchema = objectSchema/, 'Secret file scan route should use a runtime payload schema');
assert.match(opsRoutes, /parseBody\(req, res, worktreeValidateSchema\)/, 'Worktree validation route should parse bodies through runtime schemas');
assert.match(opsRoutes, /\/api\/checkpoints/, 'Checkpoint routes should live in the ops route module');
assert.match(opsRoutes, /\/api\/worktrees/, 'Worktree routes should live in the ops route module');
assert.match(opsRoutes, /\/api\/protected\/rules/, 'Protected path routes should live in the ops route module');
assert.match(opsRoutes, /\/api\/processes/, 'Process ledger routes should live in the ops route module');
assert.match(opsRoutes, /\/api\/safety\/summary/, 'Safety summary route should live in the ops route module');
assert.match(patchProposalRoutes, /export function registerPatchProposalRoutes/, 'Patch proposal routes should live outside the server entrypoint');
assert.match(patchProposalRoutes, /\/api\/patch-proposals/, 'Patch proposal CRUD routes should live in the patch proposal route module');
assert.match(patchProposalRoutes, /\/api\/patch-proposals\/:id\/isolate/, 'Patch proposal isolate route should live in the patch proposal route module');
assert.match(patchProposalRoutes, /\/api\/patch-proposals\/:id\/apply/, 'Patch proposal apply route should live in the patch proposal route module');
assert.match(patchProposalRoutes, /ensureAskBeforeWriteApproval/, 'Patch proposal write routes should preserve ask-before-write approval checks');
assert.match(patchProposalRoutes, /app\.post\('\/api\/patch-proposals\/:id\/validate'[\s\S]*ensureWorkspaceMutationAllowed/, 'Patch proposal validate should require workspace mutation control before running stored commands');
assert.match(patchProposalRoutes, /app\.post\('\/api\/patch-proposals\/:id\/commit'[\s\S]*ensureWorkspaceMutationAllowed/, 'Patch proposal commit should require workspace mutation control before running stored commands');
assert.match(patchProposalRoutes, /isPathAllowed/, 'Patch proposal apply routes should preserve trust-mode path checks');
assert.match(patchProposalRoutes, /runValidationGate/, 'Patch proposal validation and commit gates should remain in the extracted route');
assert.match(patchProposalRoutes, /captureDetectedPreview/, 'Patch proposal preview capture should remain in the extracted route');
assert.doesNotMatch(serverIndex, /app\.(get|post|patch|delete)\('\/api\/patch-proposals/, 'Patch proposal routes should not remain inline in the server entrypoint');
assert.match(projectMemoryRoutes, /export function registerProjectMemoryRoutes/, 'Project memory routes should live outside the server entrypoint');
assert.match(projectMemoryRoutes, /\/api\/project\/memory/, 'Project memory read and write routes should live in the project memory route module');
assert.match(projectMemoryRoutes, /\/api\/project\/memory\/append/, 'Project memory append route should live in the project memory route module');
assert.match(projectMemoryRoutes, /\/api\/project\/memory\/archive/, 'Project memory archive route should live in the project memory route module');
assert.match(projectMemoryRoutes, /\/api\/project\/memory\/export/, 'Project memory export route should live in the project memory route module');
assert.match(projectMemoryRoutes, /ensureWorkspaceMutationAllowed/, 'Project memory mutations should preserve workspace mutation checks after extraction');
assert.match(projectRepoRoutes, /export function registerProjectRepoRoutes/, 'Project profile and repo-map routes should live outside the server entrypoint');
assert.match(projectRepoRoutes, /\/api\/project\/profile/, 'Project profile route should live in the project repo route module');
assert.match(projectRepoRoutes, /\/api\/repo\/map/, 'Repo map route should live in the project repo route module');
assert.match(projectRepoRoutes, /\/api\/repo\/symbol/, 'Repo symbol route should live in the project repo route module');
assert.match(projectRepoRoutes, /\/api\/repo\/deps/, 'Repo dependency route should live in the project repo route module');
assert.match(projectRepoRoutes, /\/api\/repo\/impact/, 'Repo impact route should live in the project repo route module');
assert.match(projectRepoRoutes, /\/api\/repo\/context-pack/, 'Repo context-pack routes should live in the project repo route module');
assert.match(projectRepoRoutes, /validateRepoQueryPath/, 'Project repo routes should preserve repo path validation after extraction');
assert.match(projectRepoRoutes, /validateRepoFiles/, 'Project repo file routes should preserve file path validation after extraction');
assert.match(routerRoutes, /export function registerRouterRoutes/, 'Router routes should live outside the server entrypoint');
assert.match(routerRoutes, /\/api\/router\/state/, 'Auto-router state route should live in the router route module');
assert.match(routerRoutes, /\/api\/router\/learning/, 'Router learning routes should live in the router route module');
assert.match(sessionRoutes, /export function registerSessionRoutes/, 'Session routes should live outside the server entrypoint');
assert.match(sessionRoutes, /auditRouteMutation/, 'Session route mutations should use centralized audit logging');
assert.match(sessionRoutes, /createSessionSchema = objectSchema/, 'Session create route should use a runtime payload schema');
assert.match(sessionRoutes, /steeringSchema = objectSchema/, 'Session steering route should use a runtime payload schema');
assert.match(sessionRoutes, /validationProofSchema = objectSchema/, 'Validation proof route should use a runtime payload schema');
assert.match(sessionRoutes, /\/api\/sessions/, 'Session list/create/read/delete routes should live in the session route module');
assert.match(sessionRoutes, /\/api\/sessions\/:sessionId\/runs\/:runId\/steering/, 'Session run steering route should live in the session route module');
assert.match(sessionRoutes, /\/api\/sessions\/:sessionId\/validation-proof-artifacts/, 'Validation proof artifact route should live in the session route module');
assert.match(systemRoutes, /export function registerSystemRoutes/, 'System utility routes should live outside the server entrypoint');
assert.match(systemRoutes, /\/api\/ready/, 'Readiness route should live in the system route module');
assert.match(systemRoutes, /\/api\/dialog\/open-folder/, 'Native folder dialog route should live in the system route module');
assert.match(systemRoutes, /\/api\/cost\/estimate/, 'Cost estimate route should live in the system route module');
assert.match(systemRoutes, /x-openharness-electron-handshake/, 'System readiness route should preserve Electron handshake checks');
assert.match(systemRoutes, /estimateCost/, 'System cost route should preserve cost estimation behavior');
assert.doesNotMatch(serverIndex, /app\.(get|post)\('\/api\/(ready|dialog\/open-folder|cost\/estimate)/, 'System utility routes should not remain inline in the server entrypoint');
assert.match(taskRoutes, /export function registerTaskRoutes/, 'Harness task routes should live outside the server entrypoint');
assert.match(taskRoutes, /\/api\/tasks/, 'Harness task CRUD routes should live in the task route module');
assert.match(taskRoutes, /\/api\/task-suites/, 'Task suite routes should live in the task route module');
assert.match(taskRoutes, /validateHarnessTaskInput/, 'Task route module should preserve task payload validation');
assert.match(taskRoutes, /checkCommandPolicy/, 'Task route module should preserve command policy checks');
assert.match(taskRoutes, /ensureKnownWorkspace/, 'Task route module should preserve workspace boundary checks');
assert.doesNotMatch(serverIndex, /app\.(get|post|put|delete)\('\/api\/tasks/, 'Harness task routes should not remain inline in the server entrypoint');
assert.doesNotMatch(serverIndex, /app\.(get|post|delete)\('\/api\/task-suites/, 'Task suite routes should not remain inline in the server entrypoint');
assert.match(testRoutes, /export function registerTestRoutes/, 'Test harness routes should live outside the server entrypoint');
assert.match(testRoutes, /\/api\/test\/run/, 'Test run route should live in the test route module');
assert.match(testRoutes, /\/api\/test\/status/, 'Test status route should live in the test route module');
assert.match(testRoutes, /\/api\/test\/batch/, 'Test batch route should live in the test route module');
assert.match(testRoutes, /ensureWorkspaceReadAllowed/, 'Test routes should preserve workspace read checks');
assert.match(testRoutes, /resolveProviderForModel/, 'Test routes should preserve provider resolution behavior');
assert.match(testRoutes, /streamModel/, 'Test routes should preserve streamModel execution behavior');
assert.match(testRoutes, /disposeEphemeralSession/, 'Test routes should clean up ephemeral sessions after execution');
assert.doesNotMatch(serverIndex, /app\.(get|post)\('\/api\/test\//, 'Test harness routes should not remain inline in the server entrypoint');
assert.match(usageRoutes, /export function registerUsageRoutes/, 'Usage routes should live outside the server entrypoint');
assert.match(usageRoutes, /\/api\/usage/, 'Usage summary route should live in the usage route module');
assert.match(usageRoutes, /\/api\/usage\/record/, 'Usage record route should live in the usage route module');
assert.match(usageRoutes, /\/api\/usage\/check/, 'Usage budget check route should live in the usage route module');
assert.match(usageRoutes, /getAllUsageSummaries/, 'Usage route should keep usage summary behavior after extraction');

assert.match(ciWorkflow, /ubuntu-latest[\s\S]*macos-latest[\s\S]*windows-latest/, 'CI should validate Linux, macOS, and Windows');
assert.match(ciWorkflow, /node-version: '24'/, 'CI should use the supported Node 24 runtime');
assert.match(ciWorkflow, /npm ci[\s\S]*npm run lint[\s\S]*npm test[\s\S]*npm run build/, 'CI should run clean install, lint, test, and build');

const mcpRoutes = readFileSync('server/routes/mcpRoutes.ts', 'utf-8');
assert.match(mcpRoutes, /validateCustomStdioTrust/, 'Custom stdio MCP lifecycle should have an explicit trust-mode gate');
assert.match(mcpRoutes, /Custom stdio MCP servers require full-local trust mode/, 'Custom stdio MCP servers should require full-local trust mode');

assert.match(autoRouter, /recommendationModelKeyVariants/, 'Auto-Router should compare normalized recommendation model variants');
assert.match(routingPane, /modelKeyMatches/, 'Routing Learning should use symmetric model-key matching');
assert.match(settingsModal, /modelRecommendationMatches/, 'Settings Auto-Router recommendations should use shared symmetric matching');
assert.match(settingsModal, /from '\.\/settings\/InfoSettingsPanes'/, 'Settings informational panes should be split out of SettingsModal');
assert.match(infoSettingsPanes, /export function ChatSettingsPane/, 'Chat settings pane should live outside SettingsModal');
assert.match(infoSettingsPanes, /export function ReleaseNotesPane/, 'Release notes pane should live outside SettingsModal');
assert.match(infoSettingsPanes, /export function CrashReportsPane/, 'Crash reports pane should live outside SettingsModal');
assert.match(infoSettingsPanes, /export function AboutPane/, 'About pane should live outside SettingsModal');
assert.match(settingsModal, /from '\.\/settings\/PreferenceSettingsPanes'/, 'Settings preference panes should be split out of SettingsModal');
assert.match(preferenceSettingsPanes, /export function PersonalityPane/, 'Personality pane should live outside SettingsModal');
assert.match(preferenceSettingsPanes, /export function PersonalizationPane/, 'Personalization pane should live outside SettingsModal');
assert.match(preferenceSettingsPanes, /export function ThemePane/, 'Theme pane should live outside SettingsModal');
assert.match(preferenceSettingsPanes, /importThemePluginFromJson/, 'Theme import behavior should remain in the extracted preference pane');
assert.match(settingsModal, /from '\.\/settings\/AssistantSettingsPanes'/, 'Assistant settings panes should be split out of SettingsModal');
assert.match(assistantSettingsPanes, /export function ClickySettingsPane/, 'Clicky pane should live outside SettingsModal');
assert.match(assistantSettingsPanes, /export function AssistantCapabilityPane/, 'Assistant skills and plugins pane should live outside SettingsModal');
assert.match(assistantSettingsPanes, /export function AssistantMemoryPane/, 'Assistant memory pane should live outside SettingsModal');
assert.match(assistantSettingsPanes, /api\.getCapabilities/, 'Assistant capability loading behavior should remain in the extracted pane');
assert.match(settingsModal, /from '\.\/settings\/McpSettingsPanes'/, 'MCP settings panes should be split out of SettingsModal');
assert.match(mcpSettingsPanes, /export function DockerMCPPane/, 'Docker MCP pane should live outside SettingsModal');
assert.match(mcpSettingsPanes, /export function CuratedMCPPane/, 'Curated MCP pane should live outside SettingsModal');
assert.match(mcpSettingsPanes, /export function CustomMCPServersPane/, 'Custom MCP servers pane should live outside SettingsModal');
assert.match(mcpSettingsPanes, /export function AddMCPServerPane/, 'Add MCP server pane should live outside SettingsModal');
assert.match(mcpSettingsPanes, /api\.getDockerReadiness/, 'Docker MCP readiness behavior should remain in the extracted pane');
assert.match(mcpSettingsPanes, /api\.installCuratedMcpServer/, 'Curated MCP install behavior should remain in the extracted pane');
assert.match(settingsModal, /from '\.\/settings\/OnboardingSettingsPanes'/, 'Onboarding pane should be split out of SettingsModal');
assert.match(onboardingSettingsPanes, /export function OnboardingPane/, 'Onboarding pane should live outside SettingsModal');
assert.match(onboardingSettingsPanes, /onRestartOnboarding/, 'Onboarding restart behavior should remain in the extracted pane');

console.log('Review remediation static checks passed.');
